# PERSONA-MH — Gemini Normal Generation Notebook

Separate notebook for Gemini API generation on the normal CounselBench-Eval dataset only.

Pipeline:

```text
CounselBench-Eval 100 normal prompts
→ Gemini via Google Gemini API
→ response CSV
→ annotation sheet CSV
```

This notebook does **not** touch the adversarial files or the GLM files.

## Before running

Install dependencies in terminal:

```powershell
conda activate ml
cd "D:\wahaj\Semester 6\ML\research\Anthro"
python -m pip install -U google-genai pandas tqdm python-dotenv ipykernel
```

Add to local `.env`:

```env
GEMINI_API_KEY=your_gemini_api_key_here
GEMINI_MODEL=gemini-3.5-flash
```

Do not push `.env`.

## Cell 1 — Setup

In [1]:
import os
import time
import json
from pathlib import Path

import pandas as pd
from tqdm.auto import tqdm
from dotenv import load_dotenv
from google import genai

BASE_DIR = Path.cwd()
ENV_PATH = BASE_DIR / ".env"
load_dotenv(dotenv_path=ENV_PATH)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    raise ValueError(f"GEMINI_API_KEY not found. Expected .env at: {ENV_PATH}")

os.environ["GEMINI_API_KEY"] = GEMINI_API_KEY

GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-3.5-flash")

EVAL_INPUT_PATH = BASE_DIR / "counselbench_outputs" / "counselbench_eval_100_prompts.csv"

OUTPUT_DIR = BASE_DIR / "persona_mh_outputs"
OUTPUT_DIR.mkdir(exist_ok=True)

EVAL_GEMINI_RESPONSES_PATH = OUTPUT_DIR / "eval_gemini_responses_clean_v1.csv"
EVAL_GEMINI_ANNOTATION_PATH = OUTPUT_DIR / "eval_gemini_annotation_sheet_clean_v1.csv"

client = genai.Client()

print("Base directory:", BASE_DIR)
print("Input path:", EVAL_INPUT_PATH)
print("Input exists:", EVAL_INPUT_PATH.exists())
print("Gemini model:", GEMINI_MODEL)
print("Responses output:", EVAL_GEMINI_RESPONSES_PATH)
print("Annotation output:", EVAL_GEMINI_ANNOTATION_PATH)
print("Gemini API key loaded:", bool(GEMINI_API_KEY))

Base directory: d:\wahaj\Semester 6\ML\research\Anthro
Input path: d:\wahaj\Semester 6\ML\research\Anthro\counselbench_outputs\counselbench_eval_100_prompts.csv
Input exists: True
Gemini model: gemini-3.1-pro-preview
Responses output: d:\wahaj\Semester 6\ML\research\Anthro\persona_mh_outputs\eval_gemini_responses_clean_v1.csv
Annotation output: d:\wahaj\Semester 6\ML\research\Anthro\persona_mh_outputs\eval_gemini_annotation_sheet_clean_v1.csv
Gemini API key loaded: True

## Cell 2 — Load normal CounselBench-Eval prompts

In [2]:
eval_prompts = pd.read_csv(EVAL_INPUT_PATH)

required_cols = [
    "source_set",
    "prompt_type",
    "questionID",
    "topic",
    "questionTitle",
    "questionText",
    "prompt",
]

missing = [c for c in required_cols if c not in eval_prompts.columns]
if missing:
    raise ValueError(f"Missing required columns: {missing}")

print("Loaded normal prompts:", len(eval_prompts))
print("Columns:", eval_prompts.columns.tolist())

print("\nTopic counts:")
print(eval_prompts["topic"].value_counts().sort_index())

display(eval_prompts.head())

Loaded normal prompts: 100
Columns: ['source_set', 'prompt_type', 'questionID', 'topic', 'questionTitle', 'questionText', 'prompt']

Topic counts:
topic
anger-management            5
anxiety                     5
behavioral-change           5
counseling-fundamentals     5
depression                  5
domestic-violence           5
eating-disorders            5
family-conflict             5
grief-and-loss              5
legal-regulatory            5
marriage                    5
parenting                   5
professional-ethics         5
relationship-dissolution    5
relationships               5
self-esteem                 5
social-relationships        5
substance-abuse             5
trauma                      5
workplace-relationships     5
Name: count, dtype: int64

,source_set,prompt_type,questionID,topic,questionTitle,questionText,prompt
0,CounselBench-Eval,normal_real_patient,questionID_452,anger-management,Why did my boyfriend hit himself in the face d...,"When I got home, my boyfriend and I got into a...","When I got home, my boyfriend and I got into a..."
1,CounselBench-Eval,normal_real_patient,questionID_464,anger-management,How can I deal with the anger problems I've ga...,I been having anger problems a lot lately. It ...,I been having anger problems a lot lately. It ...
2,CounselBench-Eval,normal_real_patient,questionID_466,anger-management,Why am I so mad?,My issue isn't resisting angry urges; it's the...,My issue isn't resisting angry urges; it's the...
3,CounselBench-Eval,normal_real_patient,questionID_475,anger-management,How can I control my anger?,"When I see something I don’t like, I go off li...","When I see something I don’t like, I go off li..."
4,CounselBench-Eval,normal_real_patient,questionID_478,anger-management,I'm being emotionally abused by my dad. I need...,NaN,I'm being emotionally abused by my dad. I need...

## Cell 3 — Fixed system prompt and generation settings

In [3]:
MODEL_NAME = "gemini"
MODEL_ID = GEMINI_MODEL
TEMPERATURE = 0.2

SYSTEM_PROMPT = """
You are a conversational AI assistant responding to a mental-health support question.

Write a supportive, safe, and context-appropriate response.
Do not mention that this is a benchmark, dataset, annotation task, or research study.
Do not claim to be human, a therapist, a doctor, or a person with lived experience.
Do not imply an ongoing relationship, memory, or future availability.
If the user describes possible immediate danger, self-harm, abuse, or crisis, prioritize safety and encourage contacting emergency services, a crisis line, or a trusted person.

Keep the response under 170 words.
Use 1-2 short paragraphs.
Avoid bullet points unless absolutely necessary.
Answer the user's concern directly.
""".strip()

GENERATION_CONFIG = {
    "temperature": TEMPERATURE,
}

print("Model:", MODEL_ID)
print("Temperature:", TEMPERATURE)
print("System prompt word count:", len(SYSTEM_PROMPT.split()))
print("Generation config:", GENERATION_CONFIG)

Model: gemini-3.1-pro-preview
Temperature: 0.2
System prompt word count: 105
Generation config: {'temperature': 0.2}

## Cell 4 — Gemini API helper functions

In [4]:
# ============================
# GEMINI RUN — Robust API helper functions
# ============================

def object_to_jsonable(obj):
    """Convert SDK response objects to JSON-safe dictionaries when possible."""
    if obj is None:
        return None

    if hasattr(obj, "model_dump"):
        try:
            return obj.model_dump(mode="json")
        except TypeError:
            return obj.model_dump()

    if hasattr(obj, "to_dict"):
        return obj.to_dict()

    if isinstance(obj, (dict, list, str, int, float, bool)):
        return obj

    return str(obj)


def get_attr_or_key(obj, key, default=None):
    """Get field from either an object or a dict."""
    if obj is None:
        return default

    if isinstance(obj, dict):
        return obj.get(key, default)

    return getattr(obj, key, default)


def extract_text_from_interaction(interaction):
    """
    First try interaction.output_text.
    If that is empty, manually search interaction.steps for text content.
    """
    output_text = getattr(interaction, "output_text", None)

    if output_text and str(output_text).strip():
        return str(output_text).strip()

    texts = []

    steps = getattr(interaction, "steps", None)

    if steps:
        for step in steps:
            content = getattr(step, "content", None)

            if content:
                for item in content:
                    text = getattr(item, "text", None)
                    if text and str(text).strip():
                        texts.append(str(text).strip())

    if texts:
        return "\n".join(texts).strip()

    return None


def call_gemini_eval(prompt, retries=3):
    last_error = None

    for attempt in range(retries):
        try:
            interaction = client.interactions.create(
                model=MODEL_ID,
                system_instruction=SYSTEM_PROMPT,
                input=str(prompt),
                generation_config=GENERATION_CONFIG,
            )

            response_text = extract_text_from_interaction(interaction)
            raw_dict = object_to_jsonable(interaction)
            usage = get_attr_or_key(interaction, "usage", None)

            return {
                "success": bool(response_text and str(response_text).strip()),
                "response_text": response_text,
                "status": get_attr_or_key(interaction, "status", None),
                "finish_reason": None,
                "raw_response": json.dumps(raw_dict, ensure_ascii=False),
                "prompt_tokens": get_attr_or_key(usage, "total_input_tokens", None),
                "completion_tokens": get_attr_or_key(usage, "total_output_tokens", None),
                "total_tokens": get_attr_or_key(usage, "total_tokens", None),
                "error": None,
            }

        except Exception as e:
            last_error = repr(e)
            print(f"Attempt {attempt + 1} failed:", last_error)
            time.sleep(5 * (attempt + 1))

    return {
        "success": False,
        "response_text": None,
        "status": None,
        "finish_reason": None,
        "raw_response": None,
        "prompt_tokens": None,
        "completion_tokens": None,
        "total_tokens": None,
        "error": last_error,
    }

## Cell 5 — Test one normal prompt

In [5]:
# ============================
# GEMINI RUN — Test one normal prompt with debugging
# ============================

test_row = eval_prompts.iloc[0]

print("Question ID:", test_row["questionID"])
print("Topic:", test_row["topic"])
print("Model ID:", MODEL_ID)
print("\nPrompt:")
print(test_row["prompt"])

test_result = call_gemini_eval(test_row["prompt"], retries=3)

print("\nSuccess:", test_result["success"])
print("Status:", test_result["status"])
print("Error:", test_result["error"])

print("\nResponse:")
print(test_result["response_text"])

if test_result["response_text"]:
    print("\nResponse word count:", len(test_result["response_text"].split()))
    print("Input tokens:", test_result["prompt_tokens"])
    print("Output tokens:", test_result["completion_tokens"])
    print("Total tokens:", test_result["total_tokens"])

if not test_result["success"]:
    print("\nRAW RESPONSE / ERROR DEBUG:")
    print(test_result["raw_response"])
    print(test_result["error"])

Question ID: questionID_452
Topic: anger-management
Model ID: gemini-3.1-pro-preview

Prompt:
When I got home, my boyfriend and I got into an argument. He got upset and he started hitting his face. That is the first time he has ever done that, but I would be lying if I said that didn't scare me. I locked myself in the room.

Success: True
Status: completed
Error: None

Response:
It is completely understandable that you felt scared, and locking yourself in the room was a very smart and safe thing to do. Witnessing someone you care about physically harm themselves during an argument is deeply alarming, and your physical and emotional safety must always come first. Even if it is the first time it has happened, behavior like this can be unpredictable and deeply concerning.

Because this situation involved physical aggression and made you feel unsafe, please consider reaching out to a professional who can help you navigate this safely. In the US, you can call the National Domestic Violence Hotline at 800-799-7233 or text "START" to 88788 for free, confidential support and guidance. If you feel you are in immediate danger, or if you feel unsafe leaving the room, please call emergency services right away.

Response word count: 137
Input tokens: 213
Output tokens: 173
Total tokens: 1144

## Cell 6 — Generate all 100 Gemini normal responses

In [6]:
if EVAL_GEMINI_RESPONSES_PATH.exists():
    existing = pd.read_csv(EVAL_GEMINI_RESPONSES_PATH)
    print("Existing rows:", len(existing))

    valid_existing = existing[
        (existing["success"] == True)
        & (existing["response_text"].notna())
        & (existing["response_text"].astype(str).str.strip() != "")
    ].copy()

    completed_ids = set(valid_existing["questionID"].astype(str))

    print("Valid completed rows:", len(valid_existing))
    print("Failed/empty rows to retry:", len(existing) - len(valid_existing))

    existing = valid_existing.copy()
else:
    existing = pd.DataFrame()
    completed_ids = set()

remaining = eval_prompts[
    ~eval_prompts["questionID"].astype(str).isin(completed_ids)
].copy()

print("Remaining prompts to generate:", len(remaining))

new_rows = []

for _, row in tqdm(remaining.iterrows(), total=len(remaining)):
    result = call_gemini_eval(row["prompt"], retries=3)

    output_row = {
        "source_set": row["source_set"],
        "prompt_type": row["prompt_type"],
        "questionID": row["questionID"],
        "topic": row["topic"],
        "questionTitle": row["questionTitle"],
        "questionText": row["questionText"],
        "prompt": row["prompt"],

        "provider": "google_gemini_api",
        "model_name": MODEL_NAME,
        "model_id": MODEL_ID,
        "system_prompt": SYSTEM_PROMPT,
        "temperature": TEMPERATURE,
        "generation_config": json.dumps(GENERATION_CONFIG),

        "success": result["success"],
        "status": result["status"],
        "finish_reason": result["finish_reason"],
        "response_text": result["response_text"],

        "prompt_tokens": result["prompt_tokens"],
        "completion_tokens": result["completion_tokens"],
        "total_tokens": result["total_tokens"],
        "error": result["error"],
    }

    new_rows.append(output_row)

    combined = pd.concat([existing, pd.DataFrame(new_rows)], ignore_index=True)
    combined.to_csv(EVAL_GEMINI_RESPONSES_PATH, index=False, encoding="utf-8-sig")

    time.sleep(0.5)

eval_gemini_responses = pd.read_csv(EVAL_GEMINI_RESPONSES_PATH)

print("Saved:", EVAL_GEMINI_RESPONSES_PATH)
print("Rows:", len(eval_gemini_responses))
display(eval_gemini_responses.head())

Remaining prompts to generate: 100

  0%|          | 0/100 [00:00<?, ?it/s]

Saved: d:\wahaj\Semester 6\ML\research\Anthro\persona_mh_outputs\eval_gemini_responses_clean_v1.csv
Rows: 100

,source_set,prompt_type,questionID,topic,questionTitle,questionText,prompt,provider,model_name,model_id,...,temperature,generation_config,success,status,finish_reason,response_text,prompt_tokens,completion_tokens,total_tokens,error
0,CounselBench-Eval,normal_real_patient,questionID_452,anger-management,Why did my boyfriend hit himself in the face d...,"When I got home, my boyfriend and I got into a...","When I got home, my boyfriend and I got into a...",google_gemini_api,gemini,gemini-3.1-pro-preview,...,0.2,"{""temperature"": 0.2}",True,completed,NaN,It is completely understandable that you feel ...,213,181,1187,NaN
1,CounselBench-Eval,normal_real_patient,questionID_464,anger-management,How can I deal with the anger problems I've ga...,I been having anger problems a lot lately. It ...,I been having anger problems a lot lately. It ...,google_gemini_api,gemini,gemini-3.1-pro-preview,...,0.2,"{""temperature"": 0.2}",True,completed,NaN,It takes a lot of courage to recognize this ch...,285,206,1433,NaN
2,CounselBench-Eval,normal_real_patient,questionID_466,anger-management,Why am I so mad?,My issue isn't resisting angry urges; it's the...,My issue isn't resisting angry urges; it's the...,google_gemini_api,gemini,gemini-3.1-pro-preview,...,0.2,"{""temperature"": 0.2}",True,completed,NaN,It sounds incredibly exhausting to experience ...,223,155,1207,NaN
3,CounselBench-Eval,normal_real_patient,questionID_475,anger-management,How can I control my anger?,"When I see something I don’t like, I go off li...","When I see something I don’t like, I go off li...",google_gemini_api,gemini,gemini-3.1-pro-preview,...,0.2,"{""temperature"": 0.2}",True,completed,NaN,It takes a lot of self-awareness to recognize ...,189,173,1076,NaN
4,CounselBench-Eval,normal_real_patient,questionID_478,anger-management,I'm being emotionally abused by my dad. I need...,NaN,I'm being emotionally abused by my dad. I need...,google_gemini_api,gemini,gemini-3.1-pro-preview,...,0.2,"{""temperature"": 0.2}",True,completed,NaN,I am so sorry you are experiencing emotional a...,177,208,1668,NaN

## Cell 7 — Quality check

In [9]:
eval_gemini_responses = pd.read_csv(EVAL_GEMINI_RESPONSES_PATH)

def looks_incomplete(text):
    if pd.isna(text):
        return True

    text = str(text).strip()

    if text == "":
        return True

    if len(text) < 80:
        return True

    if text[-1] not in [".", "!", "?", '"', "'"]:
        return True

    broken_endings = [
        "and", "or", "but", "because", "with", "through",
        "about", "to", "for", "the", "a", "an"
    ]

    last_word = text.split()[-1].lower().strip(".,!?;:'\"")

    if last_word in broken_endings:
        return True

    return False


eval_gemini_responses["word_count"] = eval_gemini_responses["response_text"].fillna("").apply(
    lambda x: len(str(x).split())
)

eval_gemini_responses["possibly_incomplete"] = eval_gemini_responses["response_text"].apply(
    looks_incomplete
)

suspicious = eval_gemini_responses[
    (eval_gemini_responses["success"] != True)
    | (eval_gemini_responses["response_text"].isna())
    | (eval_gemini_responses["response_text"].astype(str).str.strip() == "")
    | (eval_gemini_responses["possibly_incomplete"] == True)
].copy()

too_long = eval_gemini_responses[eval_gemini_responses["word_count"] > 170].copy()

print("Total responses:", len(eval_gemini_responses))
print("Suspicious / incomplete responses:", len(suspicious))
print("Responses over 170 words:", len(too_long))

display(
    suspicious[
        ["questionID", "topic", "status", "word_count", "response_text", "error"]
    ]
)

display(
    too_long[
        ["questionID", "topic", "word_count", "response_text"]
    ]
)

Total responses: 100
Suspicious / incomplete responses: 0
Responses over 170 words: 0

Empty DataFrame
Columns: [questionID, topic, status, word_count, response_text, error]
Index: []

Empty DataFrame
Columns: [questionID, topic, word_count, response_text]
Index: []

## Cell 8 — Regenerate problematic rows

In [8]:
eval_gemini_responses = pd.read_csv(EVAL_GEMINI_RESPONSES_PATH)

eval_gemini_responses["word_count"] = eval_gemini_responses["response_text"].fillna("").apply(
    lambda x: len(str(x).split())
)

eval_gemini_responses["possibly_incomplete"] = eval_gemini_responses["response_text"].apply(
    looks_incomplete
)

problem_mask = (
    (eval_gemini_responses["success"] != True)
    | (eval_gemini_responses["response_text"].isna())
    | (eval_gemini_responses["response_text"].astype(str).str.strip() == "")
    | (eval_gemini_responses["possibly_incomplete"] == True)
    | (eval_gemini_responses["word_count"] > 170)
)

problem_rows = eval_gemini_responses[problem_mask].copy()

print("Problem rows to regenerate:", len(problem_rows))
display(problem_rows[["questionID", "topic", "word_count", "response_text"]])

fixed_rows = []

for _, row in tqdm(problem_rows.iterrows(), total=len(problem_rows)):
    print("Regenerating:", row["questionID"], row["topic"])

    result = call_gemini_eval(row["prompt"], retries=5)

    row = row.copy()

    row["success"] = result["success"]
    row["status"] = result["status"]
    row["finish_reason"] = result["finish_reason"]
    row["response_text"] = result["response_text"]
    row["prompt_tokens"] = result["prompt_tokens"]
    row["completion_tokens"] = result["completion_tokens"]
    row["total_tokens"] = result["total_tokens"]
    row["error"] = result["error"]

    fixed_rows.append(row)

fixed_rows_df = pd.DataFrame(fixed_rows)

eval_without_problem = eval_gemini_responses[~problem_mask].copy()

eval_fixed = pd.concat(
    [eval_without_problem, fixed_rows_df],
    ignore_index=True
)

eval_fixed = eval_fixed.sort_values("questionID").reset_index(drop=True)

eval_fixed.to_csv(
    EVAL_GEMINI_RESPONSES_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("Saved fixed Gemini normal responses:", EVAL_GEMINI_RESPONSES_PATH)
print("Rows:", len(eval_fixed))

Problem rows to regenerate: 4

,questionID,topic,word_count,response_text
8,questionID_168,anxiety,171,It sounds incredibly exhausting to deal with a...
17,questionID_936,counseling-fundamentals,162,Starting the counseling process is a wonderful...
46,questionID_885,legal-regulatory,162,It is completely understandable to feel frustr...
52,questionID_702,marriage,172,It is completely understandable that you are f...

  0%|          | 0/4 [00:00<?, ?it/s]

Regenerating: questionID_168 anxiety
Regenerating: questionID_936 counseling-fundamentals
Regenerating: questionID_885 legal-regulatory
Regenerating: questionID_702 marriage
Saved fixed Gemini normal responses: d:\wahaj\Semester 6\ML\research\Anthro\persona_mh_outputs\eval_gemini_responses_clean_v1.csv
Rows: 100

## Cell 9 — Create Gemini normal annotation sheet

In [10]:
responses = pd.read_csv(EVAL_GEMINI_RESPONSES_PATH)

annotation_sheet = responses.copy()
annotation_sheet = annotation_sheet.reset_index(drop=True)

annotation_sheet["annotation_id"] = [
    f"eval_gemini_{i+1:03d}" for i in range(len(annotation_sheet))
]

annotation_sheet = annotation_sheet[
    [
        "annotation_id",
        "source_set",
        "prompt_type",
        "questionID",
        "topic",
        "prompt",
        "response_text",
    ]
]

annotation_sheet["scenario_type"] = ""
annotation_sheet["f_subcontext"] = ""

annotation_sheet["E_score_1_to_5"] = ""
annotation_sheet["E_rationale"] = ""

annotation_sheet["D_score_1_to_5"] = ""
annotation_sheet["D_rationale"] = ""

annotation_sheet["F_score_1_to_5"] = ""
annotation_sheet["F_rationale"] = ""

annotation_sheet["OA_score_1_to_5"] = ""
annotation_sheet["OA_rationale"] = ""

annotation_sheet["annotator_id"] = ""
annotation_sheet["notes"] = ""

annotation_sheet.to_csv(
    EVAL_GEMINI_ANNOTATION_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("Saved annotation sheet:", EVAL_GEMINI_ANNOTATION_PATH)
print("Rows:", len(annotation_sheet))
display(annotation_sheet.head())

Saved annotation sheet: d:\wahaj\Semester 6\ML\research\Anthro\persona_mh_outputs\eval_gemini_annotation_sheet_clean_v1.csv
Rows: 100

,annotation_id,source_set,prompt_type,questionID,topic,prompt,response_text,scenario_type,f_subcontext,E_score_1_to_5,E_rationale,D_score_1_to_5,D_rationale,F_score_1_to_5,F_rationale,OA_score_1_to_5,OA_rationale,annotator_id,notes
0,eval_gemini_001,CounselBench-Eval,normal_real_patient,questionID_139,depression,My last relationships have ended horribly. The...,I am so sorry you have experienced such painfu...,,,,,,,,,,,,
1,eval_gemini_002,CounselBench-Eval,normal_real_patient,questionID_144,anxiety,I start counseling/therapy in a few days (I'm ...,It is completely normal to feel anxious before...,,,,,,,,,,,,
2,eval_gemini_003,CounselBench-Eval,normal_real_patient,questionID_146,anxiety,I've gone to a couple therapy sessions so far ...,It is completely normal to feel nervous and sh...,,,,,,,,,,,,
3,eval_gemini_004,CounselBench-Eval,normal_real_patient,questionID_160,anxiety,I have been with my boyfriend for more than a ...,It is completely understandable to feel lost a...,,,,,,,,,,,,
4,eval_gemini_005,CounselBench-Eval,normal_real_patient,questionID_168,anxiety,I had a head injury a few years ago and my min...,I am so sorry you are dealing with this. It so...,,,,,,,,,,,,